version: '3'

services:
    db:
      image: yobasystems/alpine-mariadb
      volumes:
        - db-data:/var/lib/mysql
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      depends_on:
        - db
      container_name: phpmyadmin
      restart: unless-stopped
      ports:
        - 8090:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  db-data: 