version: '3'

services:
    db:
      image: yobasystems/alpine-mariadb
      volumes:
        - db-data:/var/lib/mysql
      restart: unless-stopped
      ports:
        - "3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  db-data: 