version: '3.0'

services:
  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - OPENVPN_OPTS=--auth-user-pass /etc/openvpn/credentials
    volumes:
      - ./openvpn-config/protonvpn.ovpn:/etc/openvpn/ovpn.conf
      - ./openvpn-config/vpn-credentials.txt:/etc/openvpn/credentials
    restart: unless-stopped

  pihole:
    image: cbcrowe/pihole-unbound:latest
    container_name: pihole
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_WEBPORT:-80}:80/tcp
      - 5335:5335/tcp
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
      - ./unbound-config:/etc/unbound/unbound.conf.d
      - ./unbound-logs:/var/log/unbound
    environment:
      - FTLCONF_REPLY_ADDR4=${FTLCONF_REPLY_ADDR4}
      - TZ=${TZ:-UTC}
      - WEBPASSWORD=${WEBPASSWORD}
      - WEBTHEME=${WEBTHEME:-default-light}
      - REV_SERVER=${REV_SERVER:-false}
      - REV_SERVER_TARGET=${REV_SERVER_TARGET}
      - REV_SERVER_DOMAIN=${REV_SERVER_DOMAIN}
      - REV_SERVER_CIDR=${REV_SERVER_CIDR}
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single
    network_mode: "service:vpn" # Use VPN network
    depends_on:
      - vpn
    restart: unless-stopped

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:
  unbound-config:
