version: '3.1'

services:
    certbot:
      image: certbot/certbot
      container_name: letsencrypt-certbot
      volumes:
        - ./files/data:/etc/letsencrypt
        - ./files/var:/var/lib/letsencrypt
      # This command its for the first time ssl generation
      command: certonly --manual --preferred-challenges dns --email danfercf@gmail.com --agree-tos --no-eff-email --force-renewal --agree-tos --no-eff-email --debug-challenges -v -d ${CERTBOT_DOMAIN}
      #command: renew --force-renewal