version: '3'

services:

  phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
          - 8090:80
        environment:
          PMA_HOST: ${PMA_HOST}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}