version: '3'

services:
  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest
    container_name: tvheadend
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      RUN_OPTS: ${RUN_OPTS}
    volumes:
      - ./config:/config
      - ./recordings:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    restart: unless-stopped